-- TemplateRecovery owns candidate sampling and the single ring queue that feeds
-- cell repair. Candidate cells are generated around the RV active players on the
-- configured sample interval, queued without duplicates, and drained under a
-- fixed per-tick budget. The Boundary sweep calls onPostPlayerTick directly
-- after it has validated the active players and boundaries; this module
-- registers no callback and the published instance is looked up at runtime
-- through RailroaderRV.RecoveryQueue.
local instance = nil
return function(ctx)
if instance then return instance end
local Core = ctx.Core
local Constants = ctx.Constants
local ServerUtil = ctx.ServerUtil
local Repair = require("RailroaderRV/TemplateRecovery/RV_Server_TemplateProtectionRepair")(ctx)

-- One ring buffer is shared by every RV. It holds only queued cell coordinates
-- plus the identity of the generation that queued them; cells generated by an
-- older generation of the same RV are still checked against the current
-- template when their turn comes. `head = 1, tail = 0` is the canonical empty
-- state: the queued window is `head .. tail` when it does not wrap and
-- `head .. CAPACITY` plus `1 .. tail` when it does.
local CAPACITY = 256
local queue = {
    entries = {},
    head = 1,
    tail = 0,
    count = 0,
}

local sampleInterval = Constants.TEMPLATE_PROTECTION_REPAIR_SAMPLE_INTERVAL_TICKS

-- Duplicate suppression scans the whole queued window; nothing outside the ring
-- is tracked, so a cell may be queued again after it has been checked. The wrap
-- test is count-guarded: the empty state (`tail = 0`) also satisfies
-- `tail < head`.
local function queuedWindowWraps()
    return queue.count > 0 and queue.tail < queue.head
end

local function enqueueCell(rvId, generation, x, y)
    if queue.count == CAPACITY then return false end
    local wrapped = queuedWindowWraps()
    local last = wrapped and CAPACITY or queue.tail
    for index = queue.head, last do
        local entry = queue.entries[index]
        if entry.x == x and entry.y == y then return false end
    end
    if wrapped then
        for index = 1, queue.tail do
            local entry = queue.entries[index]
            if entry.x == x and entry.y == y then return false end
        end
    end
    queue.tail = queue.tail % CAPACITY + 1
    queue.entries[queue.tail] = {
        rvId = rvId, generation = generation, x = x, y = y,
    }
    queue.count = queue.count + 1
    return true
end

local function dequeueCell()
    if queue.count == 0 then return nil end
    local entry = queue.entries[queue.head]
    queue.entries[queue.head] = nil
    queue.count = queue.count - 1
    if queue.count == 0 then
        queue.head, queue.tail = 1, 0
    else
        queue.head = queue.head % CAPACITY + 1
    end
    return entry
end

-- Fixed budget: a deeper queue only widens how many cells one tick may check.
local function tickBudget()
    if queue.count > 128 then return 4 end
    if queue.count > 64 then return 2 end
    return 1
end

-- The sweep already validated this player's boundary and passed it along, so
-- the queued identity comes from there; the live boundary is re-checked when the
-- cell is actually checked.
local function enqueuePlayerCells(item)
    local player = item.player
    local boundary = item.boundary
    if player == nil or boundary == nil then return end
    local xOk, playerX = ServerUtil.invoke(player, "getX")
    local yOk, playerY = ServerUtil.invoke(player, "getY")
    local x, y = xOk and ServerUtil.toNumber(playerX),
        yOk and ServerUtil.toNumber(playerY)
    if not x or not y then return end
    local centerX, centerY = math.floor(x), math.floor(y)
    for offsetY = -1, 1 do
        for offsetX = -1, 1 do
            local cellX, cellY = centerX + offsetX, centerY + offsetY
            if Repair.isProtectedCell(boundary, cellX, cellY) then
                enqueueCell(tostring(boundary.rvId), boundary.generation,
                    cellX, cellY)
            end
        end
    end
end

-- A queued cell is checked through a player of its own RV generation. A cell
-- whose generation has no active player is dropped rather than left blocking
-- the head of the ring.
local function findQueuedPlayer(activePlayers, entry)
    for index = 1, #activePlayers do
        local item = activePlayers[index]
        local boundary = item and item.boundary
        if item and item.player and boundary
            and tostring(boundary.rvId) == entry.rvId
            and boundary.generation == entry.generation then
            return item.player, boundary
        end
    end
    return nil, nil
end

local function processQueuedCells(activePlayers)
    local budget = tickBudget()
    local checked = 0
    while checked < budget do
        local entry = dequeueCell()
        if not entry then break end
        local player, boundary = findQueuedPlayer(activePlayers, entry)
        if player then
            local x, y = entry.x, entry.y
            local repaired, reason = Repair.repairCell(player,
                boundary, x, y)
            if repaired == false and reason ~= nil then
                print("[RailroaderRV] template-protection-repair skipped "
                    .. "cell " .. tostring(x) .. "," .. tostring(y) .. ": "
                    .. tostring(reason))
            end
            checked = checked + 1
        end
    end
end

local function onPostPlayerTick(tick, activePlayers, activeBoundaries)
    if type(activePlayers) ~= "table" then
        return false, "active player list is unavailable"
    end
    -- An in-flight relocation or roof refresh can leave the player outside the
    -- template for a few ticks; that cell check simply waits for the next one.
    if Core.tickModulo(sampleInterval) then
        for index = 1, #activePlayers do
            enqueuePlayerCells(activePlayers[index])
        end
    end
    processQueuedCells(activePlayers)
    return true
end

instance = {
    onPostPlayerTick = onPostPlayerTick,
}
RailroaderRV = RailroaderRV or {}
RailroaderRV.RecoveryQueue = instance
return instance
end
