-- Shared names and fixed values for the current RV water implementation.
-- Water state and all world or inventory changes remain server-owned.

local M = {}

M.OP_INSTALL_WATER_TANK = "INSTALL_WATER_TANK"
M.OP_REMOVE_WATER_TANK = "REMOVE_WATER_TANK"
M.OP_INSTALL_SUPPLY_PUMP = "INSTALL_SUPPLY_PUMP"
M.OP_INSTALL_EXTRACTION_PUMP = "INSTALL_EXTRACTION_PUMP"
M.OP_REMOVE_EXTRACTION_PUMP = "REMOVE_EXTRACTION_PUMP"
M.OP_INSTALL_WATER_FILTER = "INSTALL_WATER_FILTER"
M.OP_REMOVE_WATER_FILTER = "REMOVE_WATER_FILTER"
M.OP_ADD_WATER_FROM_CONTAINER = "ADD_WATER_FROM_CONTAINER"
M.OP_DRAW_WATER_FROM_SOURCE = "DRAW_WATER_FROM_SOURCE"

M.WATER_TANK_ITEM = "RailroaderRV.WaterTank"
M.SMALL_PUMP_ITEM = "RailroaderRV.WaterPumpSmall"
M.INDUSTRIAL_PUMP_ITEM = "RailroaderRV.WaterPumpIndustrial"
M.WATER_FILTER_ITEM = "RailroaderRV.WaterFilter"

M.LITERS_PER_TANK = 1000
M.MAX_WATER_TANKS = 2
M.FILTER_CONDITION_MAX = 127
M.FILTER_CAPACITY_L = 5000
M.CONTAINER_FLOW_L_PER_MINUTE = 40
M.SMALL_PUMP_FLOW_L_PER_MINUTE = 40
M.INDUSTRIAL_PUMP_FLOW_L_PER_MINUTE = 200
M.SMALL_PUMP_WATTS = 20
M.INDUSTRIAL_PUMP_WATTS = 100
M.SUPPLY_PUMP_WATTS = 20
M.NATURAL_SOURCE_RADIUS = 10

function M.remainingFilterLiters(water)
    if water.filter == nil then return 0 end
    return M.FILTER_CAPACITY_L * water.filter.condition
        / M.FILTER_CONDITION_MAX
end

return M
