-- Shared current-schema contract for the RV water/electric utility layer.
--
-- This module is deliberately data-only.  It does not resolve world objects,
-- read client coordinates, or mutate a FluidContainer.  The server modules
-- are the only authority for all values below.

require("RailroaderRV/Common/RV_Constants")
RailroaderRV = RailroaderRV or {}
RailroaderRV.UtilityConstants = RailroaderRV.UtilityConstants or {}

local U = RailroaderRV.UtilityConstants

U.STORE_KEY = "RailroaderRVTest.Utility"
U.POWER = require("RailroaderRV/Power/RV_UtilityPowerConfig")
require("RailroaderRV/Power/RV_UtilityItems")
U.DEVICE_REACH = 3.0
U.MAX_REQUEST_ID_LENGTH = 96

U.OP_CONNECT_WATER_DEVICE = "CONNECT_WATER_DEVICE"
U.OP_ADD_FUEL = "ADD_FUEL"
U.OP_ADD_BATTERY = "ADD_BATTERY"
U.OP_REMOVE_BATTERY = "REMOVE_BATTERY"
U.OP_INSTALL_CHARGER = "INSTALL_CHARGER"
U.OP_REMOVE_CHARGER = "REMOVE_CHARGER"
U.OP_INSTALL_INVERTER = "INSTALL_INVERTER"
U.OP_REMOVE_INVERTER = "REMOVE_INVERTER"
U.OP_REFRESH_DEVICES = "REFRESH_DEVICES"
U.OP_REQUEST_SNAPSHOT = "REQUEST_SNAPSHOT"
U.OP_START_GENERATOR = "START_GENERATOR"
U.OP_STOP_GENERATOR = "STOP_GENERATOR"

U.WATER_STATE_ACTIVE = "ACTIVE"
U.POWER_STATE_READY = "READY"
U.CIRCUIT_OFF = "OFF"
U.CIRCUIT_ON = "ON"

-- Stable reason codes are intentionally ASCII and transport-safe.
U.REASONS = {
    OK = "OK",
    BUSY = "UTILITY_BUSY",
    INVALID_REQUEST = "UTILITY_INVALID_REQUEST",
    PERMISSION = "UTILITY_PERMISSION_DENIED",
    RV_NOT_FOUND = "UTILITY_RV_NOT_FOUND",
    OUTSIDE_RV = "UTILITY_OUTSIDE_RV",
    TARGET_NOT_LOADED = "UTILITY_TARGET_NOT_LOADED",
    MISSING_TOOL = "UTILITY_MISSING_TOOL",
    DEVICE_NOT_SUPPORTED = "UTILITY_DEVICE_NOT_SUPPORTED",
    DEVICE_INVALID = "UTILITY_DEVICE_INVALID",
    DEVICE_NOT_CURRENT = "UTILITY_DEVICE_NOT_CURRENT",
    SOURCE_INVALID = "UTILITY_SOURCE_INVALID",
    SOURCE_NOT_INVENTORY = "UTILITY_SOURCE_NOT_INVENTORY",
    CAPACITY_FULL = "UTILITY_CAPACITY_FULL",
    API_ERROR = "UTILITY_API_ERROR",
    CANONICAL_COMMIT_FAILED = "UTILITY_CANONICAL_COMMIT_FAILED",
    POSTCONDITION_FAILED = "UTILITY_POSTCONDITION_FAILED",
    GENERATOR_INVALID = "UTILITY_GENERATOR_INVALID",
}

U.REASON_INVALID_RV_DATA = "INVALID_RV_DATA"

return U
