-- Captured from the user's 2026-09-25 server layout log.
-- Coordinates are relative to the captured player cell (51,44,0), which
-- is aligned to the generated RV arrival anchor. Do not infer old templates.
-- snapshots require every captured identity field used by the generator.
-- Cab build cells are part of the authored template contract. Keep them
-- explicit so client and server consume the same immutable layout data.
local buildCells = {
    { x = -4, y = -2 }, { x = -4, y = -1 }, { x = -4, y = 0 }, { x = -4, y = 1 },
    { x = -3, y = -2 }, { x = -3, y = -1 }, { x = -3, y = 0 }, { x = -3, y = 1 },
    { x = -2, y = -2 }, { x = -2, y = -1 }, { x = -2, y = 0 }, { x = -2, y = 1 },
    { x = -1, y = -2 }, { x = -1, y = -1 }, { x = -1, y = 0 }, { x = -1, y = 1 },
    { x = 0, y = -2 }, { x = 0, y = -1 }, { x = 0, y = 0 }, { x = 0, y = 1 },
    { x = 1, y = -2 }, { x = 1, y = -1 }, { x = 1, y = 0 }, { x = 1, y = 1 },
}

return {
    schemaVersion = 9,
    sourceTarget = { x = 51, y = 44, z = 0 },
    objectCount = 412,
    -- Cab z0 build/demolish permission is the full 6x4 rectangle. The
    -- proximity queue exempts only these captured template cells.
    buildCells = buildCells,
    objects = {
    {x=-4, y=-6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_13", direction="N", state={hoppable=false}},
    {x=-4, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=-6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=-5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=-5, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=-5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=-5, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=-4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=-4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=-4, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=-3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_12", direction="N", state={hoppable=false}},
    {x=-4, y=-3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=-3, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=-2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-4, y=-2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-4, y=-2, z=0, class="IsoThumpable", name="Wooden Door Frame", sprite="walls_interior_house_02_43", north=true, direction="N", state={health=300,hoppable=false,locked=false,maxHealth=300}},
    {x=-4, y=-2, z=0, class="IsoDoor", name="Wooden Door", sprite="location_restaurant_pileocrepe_01_49", north=true, direction="N", state={}},
    {x=-4, y=-1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-4, y=-1, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_10_28", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-4, y=-1, z=0, class="IsoWindow", name="Window", sprite="fixtures_windows_metal_28", north=false, direction="N", state={health=50,hoppable=false,locked=false}},
    {x=-4, y=-1, z=0, class="IsoThumpable", name="Thumpable", sprite="furniture_seating_indoor_01_51", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-4, y=0, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-4, y=0, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_10_24", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-4, y=0, z=0, class="IsoWindow", name="Window", sprite="fixtures_windows_metal_24", north=false, direction="N", state={health=50,hoppable=false,locked=false}},
    {x=-4, y=1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-4, y=1, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-4, y=1, z=0, class="IsoThumpable", name="Thumpable", sprite="furniture_seating_indoor_01_51", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-4, y=2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_41", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-4, y=2, z=0, class="IsoWindow", name="Window", sprite="fixtures_windows_01_33", north=true, direction="N", state={health=50,hoppable=false,locked=false}},
    {x=-4, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=2, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=3, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=4, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=5, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=7, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=7, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=7, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=8, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=8, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=8, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=9, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=9, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=9, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=10, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=10, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=10, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=11, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=11, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=11, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=12, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=12, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=12, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=13, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=13, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=13, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=14, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=14, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=14, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=15, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=-4, y=15, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=15, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=16, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_13", direction="N", state={hoppable=false}},
    {x=-4, y=16, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=17, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-4, y=17, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-3, y=-6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=-3, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-3, y=-6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-3, y=-5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=-4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=-4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-3, y=-4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=-3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=-3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=-2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=-2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=-2, z=0, class="IsoLightSwitch", name="LightSwitch", sprite="lighting_outdoor_01_40", direction="N", state={hoppable=false}},
    {x=-3, y=-1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=0, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=7, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=7, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=8, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=8, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=9, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=9, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=10, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=10, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=11, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=11, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=12, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=12, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=13, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=13, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=14, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=14, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-3, y=15, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-3, y=15, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-3, y=16, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=-3, y=17, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-3, y=17, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-2, y=-6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=-2, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-2, y=-6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-2, y=-5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=-5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-2, y=-5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=-4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=-4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_35", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-2, y=-3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=-2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=-2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=-1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=0, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=7, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=8, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=9, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=10, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=11, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=12, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=13, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=14, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=15, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-2, y=15, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-2, y=16, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=-2, y=16, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=-2, y=17, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-2, y=17, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-1, y=-6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=-1, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-1, y=-6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-1, y=-5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=-5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=-4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=-3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=-2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=-2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=-1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=0, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=7, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=8, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=9, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=10, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=11, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=12, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=13, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=14, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=15, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=-1, y=16, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=-1, y=16, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=-1, y=17, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=-1, y=17, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=0, y=-6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=0, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=0, y=-6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=0, y=-5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=-5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=0, y=-4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=-4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=0, y=-3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=-2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=-2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=-2, z=0, class="IsoLightSwitch", name="LightSwitch", sprite="lighting_outdoor_01_40", direction="N", state={hoppable=false}},
    {x=0, y=-2, z=0, class="IsoThumpable", name="Thumpable", sprite="appliances_com_01_52", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=0, y=-1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=0, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=7, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=8, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=9, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=10, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=11, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=12, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=13, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=14, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=15, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=0, y=15, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=0, y=15, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=0, y=16, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_37", direction="N", state={hoppable=false}},
    {x=0, y=16, z=0, class="IsoObject", name="Wooden Wall", sprite="walls_interior_house_02_35", direction="N", state={}},
    {x=0, y=17, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=0, y=17, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=1, y=-6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_13", direction="N", state={hoppable=false}},
    {x=1, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=1, y=-6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=1, y=-5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=-5, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=1, y=-4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=-4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=1, y=-3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=-3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=1, y=-2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=1, y=-2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_41", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200,canPassThrough=true}},
    {x=1, y=-2, z=0, class="IsoWindow", name="Window", sprite="fixtures_windows_01_33", north=true, direction="N", state={health=50,hoppable=false,locked=false}},
    {x=1, y=-2, z=0, class="IsoThumpable", name="Thumpable", sprite="appliances_com_01_52", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=-1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=1, y=-1, z=0, class="IsoThumpable", name="Thumpable", sprite="furniture_seating_indoor_01_51", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=0, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=1, y=1, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_39", direction="N", state={hoppable=false}},
    {x=1, y=2, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_12", direction="N", state={hoppable=false}},
    {x=1, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=2, z=0, class="IsoThumpable", name="Wooden Door Frame", sprite="walls_interior_house_02_43", north=true, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=1, y=2, z=0, class="IsoDoor", name="Wooden Door", sprite="location_restaurant_pileocrepe_01_49", north=true, direction="N", state={}},
    {x=1, y=3, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=4, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=1, y=5, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=6, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=7, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=7, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=8, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=8, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=9, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=9, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=10, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=10, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=11, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=11, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=12, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=12, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=13, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=13, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=14, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=14, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250}},
    {x=1, y=15, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_38", direction="N", state={hoppable=false}},
    {x=1, y=15, z=0, class="IsoObject", name="Wooden Wall", sprite="walls_interior_house_02_35", direction="N", state={}},
    {x=1, y=16, z=0, class="IsoObject", name="IsoObject", sprite="industry_01_13", direction="N", state={hoppable=false}},
    {x=1, y=16, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=1, y=17, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_33", north=true, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=1, y=17, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_37", north=true, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=-5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=-5, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=-4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=-4, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=-3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=-3, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    -- Preserve only the four east-side cab walls as explicit cab protection.
    {x=2, y=-2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=2, y=-1, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_10_28", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=2, y=-1, z=0, class="IsoWindow", name="Window", sprite="fixtures_windows_metal_28", north=false, direction="N", state={health=50,hoppable=false,locked=false}},
    {x=2, y=0, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_10_24", north=false, direction="N", state={health=350,hoppable=false,locked=false,maxHealth=350}},
    {x=2, y=0, z=0, class="IsoWindow", name="Window", sprite="fixtures_windows_metal_24", north=false, direction="N", state={health=50,hoppable=false,locked=false}},
    {x=2, y=1, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=2, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_35", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=2, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=2, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=3, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=3, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=4, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=4, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=5, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=5, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=6, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=7, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=7, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=8, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=8, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=9, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=9, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=10, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=10, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=11, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=11, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=12, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=12, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=13, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=13, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=14, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=14, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=2, y=15, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=15, z=0, class="IsoThumpable", name="Thumpable", sprite="fixtures_railings_01_36", north=false, direction="N", state={health=250,hoppable=true,locked=false,maxHealth=250}},
    {x=-4, y=-2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-4, y=-1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-4, y=0, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-4, y=1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=-4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=-3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=-2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=-1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=0, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=5, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=6, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=7, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=8, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=9, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=10, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=11, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=12, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=13, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-3, y=14, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=-5, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=-4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=-3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=-2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=-1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=0, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=5, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=6, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=7, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=8, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=9, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=10, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=11, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=12, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=13, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-2, y=14, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=150,hoppable=false,locked=false,maxHealth=150}},
    {x=-2, y=15, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=150,hoppable=false,locked=false,maxHealth=150}},
    {x=-1, y=-5, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=-4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=-3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=-2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=-1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=0, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=5, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=6, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=7, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=8, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=9, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=10, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=11, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=12, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=-1, y=13, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=150,hoppable=false,locked=false,maxHealth=150}},
    {x=-1, y=14, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=150,hoppable=false,locked=false,maxHealth=150}},
    {x=-1, y=15, z=1, class="IsoObject", name="IsoObject", sprite="location_shop_fossoil_01_39", direction="N", state={hoppable=false}},
    {x=0, y=-4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=-3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=-2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=-1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=0, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=3, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=4, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=5, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=6, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=7, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=8, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=9, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=10, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=11, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=12, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=0, y=13, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=150,hoppable=false,locked=false,maxHealth=150}},
    {x=0, y=14, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=150,hoppable=false,locked=false,maxHealth=150}},
    {x=1, y=-2, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=1, y=-1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=1, y=0, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    {x=1, y=1, z=1, class="IsoThumpable", name="Thumpable", sprite="location_shop_fossoil_01_39", north=false, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200}},
    -- Two east-facing dark fancy wardrobes sit directly west of the cab wall.
    -- Each is built from the two captured tiles in its north-facing sprite grid.
    {x=-5, y=-1, z=0, class="IsoThumpable", name="Dark Fancy Wardrobe", sprite="furniture_storage_01_24", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200,doRender=false}},
    {x=-5, y=-2, z=0, class="IsoThumpable", name="Dark Fancy Wardrobe", sprite="furniture_storage_01_25", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200,doRender=false}},
    {x=-5, y=1, z=0, class="IsoThumpable", name="Dark Fancy Wardrobe", sprite="furniture_storage_01_24", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200,doRender=false}},
    {x=-5, y=0, z=0, class="IsoThumpable", name="Dark Fancy Wardrobe", sprite="furniture_storage_01_25", north=true, direction="N", state={health=200,hoppable=false,locked=false,maxHealth=200,doRender=false}},
    -- These captured wall segments close gaps at the activity-area corners.
    -- They collide like the rest of the shell and render invisibly.
    {x=-4, y=16, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=-6, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=16, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    {x=2, y=17, z=0, class="IsoThumpable", name="Wooden Wall", sprite="walls_interior_house_02_32", north=false, direction="N", state={health=250,hoppable=false,locked=false,maxHealth=250,doRender=false}},
    },
}
