-- Shared current-schema contract for the RV water/electric utility layer.
--
-- This module is deliberately data-only.  It does not resolve world objects,
-- read client coordinates, or mutate a FluidContainer.  The server modules
-- are the only authority for all values below.

require("RailroaderRV/RV_Constants")
RailroaderRV = RailroaderRV or {}
RailroaderRV.UtilityConstants = RailroaderRV.UtilityConstants or {}

local U = RailroaderRV.UtilityConstants
local C = RailroaderRV.Constants or {}

U.STORE_KEY = "RailroaderRVTest.Utility"
U.STORE_SCHEMA_VERSION = C.UTILITY_STORE_SCHEMA_VERSION
U.WATER_SCHEMA_VERSION = C.UTILITY_WATER_SCHEMA_VERSION
U.POWER_SCHEMA_VERSION = C.UTILITY_POWER_SCHEMA_VERSION
U.WATER_CAPACITY = C.UTILITY_WATER_CAPACITY
U.SERVER_TICK_INTERVAL = 1
-- Native water callbacks collect deltas immediately; this slower cadence is
-- only the authoritative settlement/reprojection fallback for missed events.
U.WATER_SETTLEMENT_INTERVAL = 30
U.DEVICE_REACH = 3.0
U.SOURCE_REACH = 3.0
U.PROFILE_EPSILON = 0.000001
U.MAX_REQUEST_ID_LENGTH = 96
U.MAX_NONCE_LENGTH = 128
U.MAX_DEVICE_ID_LENGTH = 160
U.MAX_FINGERPRINT_LENGTH = 256

U.ENTRY_INTERNAL = "INTERNAL"
U.ENTRY_LOCOMOTIVE = "LOCOMOTIVE"
U.AUTO_REFILL_DISABLED = C.UTILITY_AUTO_REFILL_STATE

U.OP_CONNECT_WATER_DEVICE = "CONNECT_WATER_DEVICE"
U.OP_ADD_WATER = "ADD_WATER"
U.OP_ADD_FUEL = "ADD_FUEL"
U.OP_REQUEST_SNAPSHOT = "REQUEST_SNAPSHOT"
U.OP_CONNECT_GENERATOR = "CONNECT_GENERATOR"
U.OP_START_GENERATOR = "START_GENERATOR"
U.OP_STOP_GENERATOR = "STOP_GENERATOR"
U.OP_REPAIR_GENERATOR = "REPAIR_GENERATOR"

U.COMMAND = "RVUtility"
U.COMMAND_ACK = "RVUtilityAck"
U.COMMAND_SNAPSHOT = "RVUtilitySnapshot"

U.STATUS_ACTIVE = "ACTIVE"
U.STATUS_NEEDS_RECONCILE = "NEEDS_RECONCILE"
U.STATUS_DEFERRED = "DEFERRED"
U.STATUS_QUARANTINE_PENDING = "QUARANTINE_PENDING"
U.STATUS_SUSPENDED = "SUSPENDED"
U.STATUS_REBUILD_REQUIRED = "REBUILD_REQUIRED"
U.WATER_STATE_ACTIVE = "ACTIVE"
U.WATER_STATE_NEEDS_RECONCILE = "NEEDS_RECONCILE"
U.WATER_STATE_DEFERRED = "DEFERRED"
U.WATER_STATE_QUARANTINE_PENDING = "QUARANTINE_PENDING"
U.WATER_STATE_REBUILD_REQUIRED = "REBUILD_REQUIRED"
U.POWER_STATE_READY = "READY"
U.POWER_STATE_DEGRADED = "DEGRADED"
U.CIRCUIT_OFF = "OFF"
U.CIRCUIT_ON = "ON"

-- Stable reason codes are intentionally ASCII and transport-safe.
U.REASONS = {
    OK = "OK",
    BUSY = "UTILITY_BUSY",
    INVALID_REQUEST = "UTILITY_INVALID_REQUEST",
    INVALID_NONCE = "UTILITY_INVALID_NONCE",
    DUPLICATE_REQUEST = "UTILITY_DUPLICATE_REQUEST",
    PERMISSION = "UTILITY_PERMISSION_DENIED",
    RV_NOT_FOUND = "UTILITY_RV_NOT_FOUND",
    OUTSIDE_RV = "UTILITY_OUTSIDE_RV",
    TARGET_NOT_LOADED = "UTILITY_TARGET_NOT_LOADED",
    SOURCE_NOT_LOADED = "UTILITY_SOURCE_NOT_LOADED",
    MISSING_TOOL = "UTILITY_MISSING_TOOL",
    DEVICE_NOT_SUPPORTED = "UTILITY_DEVICE_NOT_SUPPORTED",
    DEVICE_NOT_VALIDATED = "UTILITY_DEVICE_NOT_VALIDATED",
    DEVICE_CONFLICT = "UTILITY_DEVICE_IDENTITY_CONFLICT",
    DEVICE_INVALID = "UTILITY_DEVICE_INVALID",
    DEVICE_NOT_CURRENT = "UTILITY_DEVICE_NOT_CURRENT",
    SOURCE_INVALID = "UTILITY_SOURCE_INVALID",
    SOURCE_NOT_INVENTORY = "UTILITY_SOURCE_NOT_INVENTORY",
    SOURCE_NOT_ENOUGH = "UTILITY_SOURCE_NOT_ENOUGH",
    CAPACITY_FULL = "UTILITY_CAPACITY_FULL",
    API_ERROR = "UTILITY_API_ERROR",
    CANONICAL_COMMIT_FAILED = "UTILITY_CANONICAL_COMMIT_FAILED",
    POSTCONDITION_FAILED = "UTILITY_POSTCONDITION_FAILED",
    PROJECTION_PENDING = "UTILITY_PROJECTION_PENDING",
    INPUT_NOT_SUPPORTED = "UTILITY_INPUT_NOT_SUPPORTED",
    AUTO_REFILL_DISABLED = "UTILITY_AUTO_REFILL_DISABLED",
    GENERATOR_INVALID = "UTILITY_GENERATOR_INVALID",
    GENERATOR_CONFLICT = "UTILITY_GENERATOR_CONFLICT",
    POWER_NOT_AVAILABLE = "UTILITY_POWER_NOT_AVAILABLE",
}

U.REASON_INVALID_RV_DATA = "INVALID_RV_DATA"

return U
